import express from 'express'
import cors from 'cors'
import Database from 'better-sqlite3'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'
import { writeFileSync, existsSync, mkdirSync } from 'fs'
import { GoogleGenAI } from '@google/genai'
import dotenv from 'dotenv'

// 環境変数読み込み
dotenv.config()

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const app = express()
const PORT = process.env.PORT || 3001

// Gemini AI クライアント初期化
const genAI = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY })

// ミドルウェア
app.use(cors())
app.use(express.json())

// 静的ファイル配信（動画）
app.use('/videos', express.static(join(__dirname, '../public/videos')))

// D1データベース接続（ローカルSQLite）
const dbPath = join(__dirname, '../.wrangler/state/v3/d1/miniflare-D1DatabaseObject/7a321e1c997ab8e153b965c9a6bb80991f6ac35f4a46ec49f72ed2d92fc44616.sqlite')
let db

try {
  db = new Database(dbPath)
  console.log('✅ Database connected:', dbPath)
} catch (error) {
  console.error('❌ Database connection failed:', error.message)
  console.log('Please run: npx wrangler d1 migrations apply youtube-ai-db --local')
}

// ヘルスチェック
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() })
})

// YouTube設定自動生成エンドポイント
app.post('/api/generate-youtube-settings', (req, res) => {
  try {
    const { character, video, music } = req.body
    
    const actionMap = {
      'singing': '歌っている',
      'dancing': '踊っている',
      'talking': '喋っている',
      'playing': '演奏している'
    }
    
    const instrumentMap = {
      'acoustic-guitar': 'アコースティックギター',
      'piano': 'ピアノ',
      'drum': 'ドラム',
      'flute': 'フルート',
      'electric-guitar': 'エレキギター',
      'violin': 'バイオリン',
      'ukulele': 'ウクレレ'
    }
    
    const genreMap = {
      'pop': 'ポップ',
      'ballad': 'バラード',
      'rock': 'ロック',
      'folk': 'フォーク',
      'jazz': 'ジャズ',
      'acoustic': 'アコースティック'
    }
    
    const action = actionMap[video.action] || video.action
    const instrument = instrumentMap[video.instrument] || video.instrument
    const genre = genreMap[music.genre] || music.genre
    const theme = video.theme || '音楽'
    
    // タイトル生成
    let title = ''
    if (video.action === 'playing' || video.action === 'singing') {
      title = `【AI生成】${theme}の${genre} | ${instrument}${action}動画`
    } else {
      title = `【AI生成】${theme}がテーマの${genre}動画`
    }
    
    // 説明文生成
    const description = `この動画はAIによって自動生成されました。

🎵 テーマ: ${theme}
🎸 ジャンル: ${genre}
${video.action === 'playing' || video.action === 'singing' ? `🎹 楽器: ${instrument}` : ''}
⏱️ 長さ: ${video.duration}秒
📐 フォーマット: ${video.aspectRatio === '9:16' ? 'YouTube Shorts' : 'YouTube動画'}

#AI生成 #${genre} #${theme} #音楽動画 #AIアート

---
Generated by AI Video Auto-Upload System`
    
    // タグ生成
    const tags = [
      'AI生成',
      'AI音楽',
      genre,
      theme,
      video.action === 'playing' || video.action === 'singing' ? instrument : '',
      video.aspectRatio === '9:16' ? 'Shorts' : '',
      music.language === 'japanese' ? '日本語' : '英語'
    ].filter(Boolean)
    
    res.json({
      success: true,
      youtube: {
        title,
        description,
        tags: tags.join(', ')
      }
    })
    
  } catch (error) {
    console.error('❌ YouTube settings generation error:', error)
    res.status(500).json({
      success: false,
      error: error.message
    })
  }
})

// AI動画生成リクエストエンドポイント（フロントエンド → AI）
app.post('/api/request-video-generation', async (req, res) => {
  try {
    const config = req.body
    const prompt = buildVideoPrompt(config)
    
    // AIに動画生成をリクエスト（実際の生成は別プロセス）
    res.json({
      success: true,
      message: 'Video generation requested. Please wait...',
      prompt: prompt,
      requestId: Date.now()
    })
  } catch (error) {
    console.error('❌ Request error:', error)
    res.status(500).json({ success: false, error: error.message })
  }
})

// 動画生成エンドポイント
app.post('/api/generate', async (req, res) => {
  try {
    const config = req.body
    console.log('📝 Generation request received:', config)

    // ステップ1: プロンプト構築
    const prompt = buildVideoPrompt(config)
    console.log('🎬 Video prompt:', prompt)

    // ステップ2: Gemini Veo 3で動画生成
    console.log('🎥 Generating video with Gemini Veo 3...')
    
    try {
      // Gemini Veo 3 API呼び出し
      const operation = await genAI.models.generateVideos({
        model: 'veo-3.0-generate-001',
        prompt: prompt,
        config: {
          personGeneration: 'allow_all'
        }
      })
      
      console.log('📦 Video generation started, operation:', operation.name)
      
      // 動画生成完了を待つ（ポーリング）
      let pollingOperation = operation
      let pollCount = 0
      const maxPolls = 60 // 最大10分（10秒x60）
      
      while (!pollingOperation.done && pollCount < maxPolls) {
        console.log(`⏳ Waiting for video generation... (${pollCount + 1}/${maxPolls})`)
        await new Promise(resolve => setTimeout(resolve, 10000)) // 10秒待機
        pollingOperation = await genAI.operations.get(pollingOperation)
        pollCount++
      }
      
      if (!pollingOperation.done) {
        throw new Error('Video generation timeout after 10 minutes')
      }
      
      console.log('✅ Video generation completed!')
      
      // 生成された動画を取得
      const generatedVideo = pollingOperation.response.generatedVideos[0]
      console.log('📹 Generated video:', generatedVideo.video.name)
      
      const videoId = Date.now()
      const videoFilename = `video_${videoId}.mp4`
      const videoPath = join(__dirname, '..', 'public', 'videos', videoFilename)
      
      // ディレクトリを作成
      const videoDir = dirname(videoPath)
      if (!existsSync(videoDir)) {
        mkdirSync(videoDir, { recursive: true })
      }
      
      // 動画をダウンロード
      console.log('📥 Downloading video...')
      const fileData = await genAI.files.download({ file: generatedVideo.video })
      writeFileSync(videoPath, fileData)
      console.log('💾 Video saved to:', videoPath)
      
    } catch (error) {
      console.error('❌ Gemini video generation failed:', error.message)
      console.log('⚠️ Falling back to placeholder')
      
      const videoId = Date.now()
      const videoFilename = `video_${videoId}.mp4`
      const videoPath = join(__dirname, '..', 'public', 'videos', videoFilename)
      
      // フォールバック: エラーメッセージを返す
      throw new Error('Video generation failed: ' + error.message)
    }
    
    // 公開URL
    const publicVideoUrl = `/videos/${videoFilename}`
    
    const videoResult = {
      videoUrl: publicVideoUrl,
      thumbnailUrl: publicVideoUrl,
      duration: config.video.duration,
      videoId: videoId
    }

    // ステップ3: データベースに保存
    if (db) {
      const stmt = db.prepare(`
        INSERT INTO videos (
          character_mode, character_image_url, character_prompt,
          action, instrument, theme, aspect_ratio, duration,
          genre, language, lyrics,
          video_url, thumbnail_url,
          youtube_title, youtube_description, youtube_tags,
          youtube_status
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `)

      const result = stmt.run(
        config.character.mode,
        config.character.imageUrl || null,
        config.character.prompt || null,
        config.video.action,
        config.video.instrument || null,
        config.video.theme,
        config.video.aspectRatio,
        config.video.duration,
        config.music.genre,
        config.music.language,
        config.music.lyrics || null,
        videoResult.videoUrl,
        videoResult.thumbnailUrl,
        config.youtube.title,
        config.youtube.description,
        config.youtube.tags,
        'pending'
      )

      console.log('✅ Saved to database, ID:', result.lastInsertRowid)
    }

    res.json({
      success: true,
      data: {
        videoUrl: videoResult.videoUrl,
        thumbnailUrl: videoResult.thumbnailUrl,
        prompt: prompt,
        youtube: config.youtube
      }
    })

  } catch (error) {
    console.error('❌ Generation error:', error)
    res.status(500).json({
      success: false,
      error: error.message
    })
  }
})

// 履歴取得エンドポイント
app.get('/api/history', (req, res) => {
  try {
    if (!db) {
      return res.json({ success: true, history: [] })
    }

    const stmt = db.prepare(`
      SELECT * FROM videos 
      ORDER BY created_at DESC 
      LIMIT 50
    `)
    const history = stmt.all()

    res.json({
      success: true,
      history: history
    })

  } catch (error) {
    console.error('❌ History fetch error:', error)
    res.status(500).json({
      success: false,
      error: error.message
    })
  }
})

// スケジュール保存エンドポイント
app.post('/api/save-schedule', (req, res) => {
  try {
    const schedule = req.body
    console.log('📅 Schedule save request:', schedule)

    if (!db) {
      return res.json({ 
        success: true, 
        message: 'スケジュールを保存しました（DB未接続）' 
      })
    }

    // 既存のスケジュールを更新
    const stmt = db.prepare(`
      UPDATE schedules SET
        enabled = ?,
        slot1_enabled = 1,
        slot1_time = ?,
        slot2_enabled = 0,
        slot2_time = NULL,
        slot3_enabled = 0,
        slot3_time = NULL,
        slot4_enabled = 0,
        slot4_time = NULL,
        privacy = ?,
        updated_at = CURRENT_TIMESTAMP
      WHERE id = 1
    `)

    stmt.run(
      schedule.enabled ? 1 : 0,
      schedule.time || null,
      schedule.privacy || 'public'
    )

    res.json({
      success: true,
      message: `スケジュールを保存しました（毎日 ${schedule.time || '未設定'}）`
    })

  } catch (error) {
    console.error('❌ Schedule save error:', error)
    res.status(500).json({
      success: false,
      error: error.message
    })
  }
})

// プロンプト構築関数
function buildVideoPrompt(config) {
  const actionMap = {
    'singing': 'singing',
    'dancing': 'dancing',
    'talking': 'talking',
    'playing': 'playing'
  }

  const instrumentMap = {
    'acoustic-guitar': 'acoustic guitar',
    'piano': 'piano',
    'drum': 'drums',
    'flute': 'flute',
    'electric-guitar': 'electric guitar',
    'violin': 'violin',
    'ukulele': 'ukulele'
  }

  let prompt = ''

  // キャラクター説明
  if (config.character.mode === 'prompt' && config.character.prompt) {
    prompt += config.character.prompt + ', '
  } else {
    prompt += 'A professional musician, '
  }

  // アクション
  const action = actionMap[config.video.action] || config.video.action
  prompt += action

  // 楽器
  if (config.video.action === 'playing' && config.video.instrument) {
    const instrument = instrumentMap[config.video.instrument] || config.video.instrument
    prompt += ` the ${instrument}`
  }

  // テーマ・ジャンル
  prompt += `, ${config.video.theme} theme, ${config.music.genre} music style`

  // 言語
  prompt += `, ${config.music.language} lyrics`

  // 歌詞（一部）
  if (config.music.lyrics) {
    const lyricsPreview = config.music.lyrics.substring(0, 100)
    prompt += `, with lyrics: "${lyricsPreview}..."`
  }

  // 品質設定
  prompt += ', professional music video quality, cinematic lighting, emotional performance'

  return prompt
}

// サーバー起動
app.listen(PORT, '0.0.0.0', () => {
  console.log(`🚀 Backend API server running on http://0.0.0.0:${PORT}`)
  console.log(`📊 Health check: http://localhost:${PORT}/health`)
})
